AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GetProfileByIDLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: yk-get-profile-by-id
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 30
      Environment:
        Variables:
          ORGANIZER_TABLE: "Organizer"
          S3_BUCKET_NAME: "tikto-orgnizer-dev"

      Code:
        ZipFile: |
          exports.handler = async (event) => {
              console.log("Placeholder Lambda Function");
              return { statusCode: 200, body: "Placeholder" };
          };
      Role: !GetAtt GetProfileByIdLambdaExecutionRole.Arn

  GetProfileByIdLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetProfileLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow DynamoDB UpdateItem operation
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Organizer

              # Allow S3 object operations
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub arn:aws:s3:::tikto-orgnizer-dev/*

              # Allow writing logs to log groups
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*

              # Basic AWS Lambda service operations
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"
  GetProfilePOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: 27sqbwaad7 # Replace with your existing API Gateway ID
      ResourceId: 78iwchywp5 # Replace with your existing resource ID
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - { LambdaArn: !GetAtt GetProfileByIDLambda.Arn }

  GetProfilePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GetProfileByIDLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:27sqbwaad7/*/POST/
