AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Env:
    Type: String
    Default: Development
    AllowedValues: 
      - Development
      - Production

Mappings:
  EnvToResources:
    Development:
      ApiGatewayId: 27sqbwaad7
      UserPoolId: eu-west-1_hgUDdjyRr
      Stage: dev
      ApiGatewayRootResourceId: 78iwchywp5
    Production:
      ApiGatewayId: 27sqbwaad7
      UserPoolId: eu-west-1_hgUDdjyRr
      Stage: prod
      ApiGatewayRootResourceId: 78iwchywp5

Resources:

  UpdateRoleApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
      ParentId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayRootResourceId] 
      PathPart: update-role

  # Lambda Function
  UpdateRoleLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: yk-update-role-api
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 30
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              console.log("Placeholder Lambda Function");
              return { statusCode: 200, body: "Placeholder" };
          };
      Environment:
        Variables:
          USERS_TABLE: "UsersTable"
          ROLE_CONFIG: "user,organizer"
          USER_POOL_ID: !FindInMap [EnvToResources, !Ref Env, UserPoolId]
      Role: !GetAtt UpdateRoleApiExecutionRole.Arn

  # API Key
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: "UpdateRoleApiKey"
      Enabled: true
      StageKeys:
        - RestApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
          StageName: !FindInMap [EnvToResources, !Ref Env, Stage]

  # Usage Plan
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: "UpdateRoleUsagePlan"
      ApiStages:
        - ApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
          Stage: !FindInMap [EnvToResources, !Ref Env, Stage]
      Throttle:
        BurstLimit: 100
        RateLimit: 50
      Quota:
        Limit: 1000
        Period: MONTH

  # API Key Association
  ApiKeyUsagePlan:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  # Lambda Execution Role
  UpdateRoleApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: updateRoleLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UsersTable"
              - Effect: Allow
                Action:
                  - cognito-idp:AdminUpdateUserAttributes
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"

  # API Gateway Lambda Integration
  UpdateRoleApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt UpdateRoleLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:27sqbwaad7/*/*/update-role"



