AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ApiGatewayRestApiId:
    Type: String
    Description: The REST API ID for API Gateway deployment
  Env:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Production

Mappings:
  EnvToResources:
    Development:
      ApiGatewayId: 27sqbwaad7
      UserPoolId: eu-west-1_hgUDdjyRr
      Stage: dev
      ApiGatewayRootResourceId: 78iwchywp5
      CognitoAuthorizerId: c0oigh
    Production:
      ApiGatewayId: 27sqbwaad7
      UserPoolId: eu-west-1_hgUDdjyRr
      Stage: prod
      ApiGatewayRootResourceId: 78iwchywp5
      CognitoAuthorizerId: c0oigh

Resources:
  UpdateRoleApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
      ParentId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayRootResourceId]
      PathPart: update-role

  # CognitoAuthorizer:
  #   Type: AWS::ApiGateway::Authorizer
  #   Properties:
  #     Name: CognitoUserPoolAuthorizer
  #     Type: COGNITO_USER_POOLS
  #     RestApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
  #     IdentitySource: method.request.header.Authorization
  #     ProviderARNs:
  #       - !Sub
  #         - "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}"
  #         - UserPoolId: !FindInMap [EnvToResources, !Ref Env, UserPoolId]

  UpdateRoleApiPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
      ResourceId: !Ref UpdateRoleApiResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !FindInMap [EnvToResources, !Ref Env, CognitoAuthorizerId]
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateRoleLambda.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Methods: "'POST, OPTIONS'"
            method.response.header.Access-Control-Allow-Headers: "'Content-Type, Authorization'"

  UpdateRoleOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !FindInMap [EnvToResources, !Ref Env, ApiGatewayId]
      ResourceId: !Ref UpdateRoleApiResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'POST, OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type, Authorization'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'true'"
            method.response.header.Access-Control-Allow-Methods: "'true'"
            method.response.header.Access-Control-Allow-Headers: "'true'"

  # Lambda Function
  UpdateRoleLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: yk-update-role-api
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 30
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              console.log("Event received:", JSON.stringify(event));
              return { statusCode: 200, body: "Placeholder" };
          };
      Environment:
        Variables:
          USERS_TABLE: "UsersTable"
          ROLE_CONFIG: "user,organizer"
          USER_POOL_ID: !FindInMap [EnvToResources, !Ref Env, UserPoolId]
      Role: !GetAtt UpdateRoleApiExecutionRole.Arn
      TracingConfig:
        Mode: Active

  # Lambda Execution Role
  UpdateRoleApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: updateRoleLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UsersTable"
              - Effect: Allow
                Action:
                  - cognito-idp:AdminUpdateUserAttributes
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"

  UpdateRoleApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt UpdateRoleLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApiId}/*
